/// Flutter icons MyIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData person_add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_2 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_bookmark = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fx = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_cancel = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_document = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_edit = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_file = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_folder = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_home = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_lock = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_music = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_ok = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_password = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_picture = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_speech_bubble = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_person = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_youtube = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_ = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user1 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user2 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_1 = IconData(0xf03d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus = IconData(0xf234, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
